// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskEdit {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl tab_schedules;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl tab_clipboard;
		
		protected System.Web.UI.WebControls.TextBox txtTaskCode;
		
		protected System.Web.UI.WebControls.TextBox txtTaskName;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.TextBox txtConcurrentInstances;
		
		protected System.Web.UI.WebControls.TextBox txtQueueDepth;
		
		protected System.Web.UI.WebControls.Label lblVersion;
		
		protected System.Web.UI.WebControls.Label lblStatus2;
		
		protected System.Web.UI.UpdatePanel udpCodeblocks;
		
		protected System.Web.UI.WebControls.Literal ltCodeblocks;
		
		protected System.Web.UI.WebControls.Button btnCBRefresh;
		
		protected System.Web.UI.WebControls.Literal ltCategories;
		
		protected System.Web.UI.WebControls.Literal ltFunctions;
		
		protected System.Web.UI.WebControls.Label lblLastRunDT;
		
		protected System.Web.UI.WebControls.Label lblLastRunStatus;
		
		protected System.Web.UI.WebControls.Image debug_view_latest_log;
		
		protected System.Web.UI.WebControls.Label lblCurrentStatus;
		
		protected System.Web.UI.UpdatePanel udpSchedule;
		
		protected System.Web.UI.WebControls.Repeater rpSchedules;
		
		protected System.Web.UI.WebControls.PlaceHolder phClipboard;
		
		protected System.Web.UI.WebControls.Label lblTaskNameHeader;
		
		protected System.Web.UI.WebControls.Label lblVersionHeader;
		
		protected System.Web.UI.WebControls.HiddenField hidCodeblockName;
		
		protected System.Web.UI.WebControls.HiddenField hidTaskID;
		
		protected System.Web.UI.WebControls.HiddenField hidOriginalTaskID;
		
		protected System.Web.UI.WebControls.HiddenField hidDefault;
		
		protected System.Web.UI.WebControls.HiddenField hidStepDelete;
		
		protected System.Web.UI.WebControls.HiddenField hidParamDelete;
		
		protected System.Web.UI.WebControls.HiddenField hidDebugActiveInstance;
		
		protected System.Web.UI.WebControls.Label lblCurrentVersion;
		
		protected System.Web.UI.WebControls.Label lblNewMinor;
		
		protected System.Web.UI.WebControls.Label lblNewMajor;
		
		protected System.Web.UI.WebControls.CheckBox chkMakeDefault;
	}
}
