// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class fileUpload {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.ScriptManager ScriptManager;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile fupFile;
		
		protected System.Web.UI.WebControls.Button btnImport;
	}
}
